name: "Build and Push to GCR"
author: "SafeHouse Tech."
description: |-
  An action to build and push docker images to GCR.
inputs:
  credentials_json:
    description: |-
      Credential file for GCP authentication.
    required: true
  project_id:
    description: |-
      GCP project ID.
    required: true
  service_id:
    description: |-
      This is the name of the service you want to build and push.
    required: true
  tag:
    description: |-
      container tag
    default: latest
  version:
    description: |-
      container tag
    required: true
  action_token:
    description: |-
      This is github action token
    required: true
  build_environment:
    description: |-
      Environment on which service needs to be publish
    default: development
  build_args:
    description: |-
      Build arguments required to build docker images
    required: false

runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v3
    - name: "gcloud auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: ${{ inputs.credentials_json }}
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ inputs.project_id }}
    - name: "Configure Docker Credentials Helper"
      shell: bash
      run: gcloud --quiet auth configure-docker
    - name: Build and publish
      shell: bash
      run: |-
        export LD_LIBRARY_PATH=/usr/local/lib
        export CLOUDSDK_PYTHON=/usr/bin/python
        if [ ! -z "${{ inputs.build_args }}" ]; then
        for ARG in $(echo "${{ inputs.build_args }}" | tr ',' '\n'); do
            BUILD_PARAMS="$BUILD_PARAMS --build-arg ${ARG}"
        done
        fi
        echo $BUILD_PARAMS
        docker build $BUILD_PARAMS -t gcr.io/${{ inputs.project_id }}/safehouse/${{ inputs.service_id }}:${{ inputs.tag }} .
        docker push gcr.io/${{ inputs.project_id }}/safehouse/${{ inputs.service_id }}:${{ inputs.tag }}

    - name: Bump version and push tag
      id: tag_version
      if: ${{ inputs.build_environment == 'production' }}
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ inputs.action_token }}
    - name: Create a GitHub release
      if: ${{ inputs.build_environment == 'production' }}
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        run: echo ${{ steps.tag_version.outputs.new_tag }}
    - name: Tag and publish
      shell: bash
      if: ${{ inputs.build_environment == 'production' }}
      run: |-
        gcloud --quiet auth configure-docker
        docker tag gcr.io/${{ inputs.project_id }}/safehouse/${{ inputs.service_id }}:${{ inputs.tag }} gcr.io/${{ inputs.project_id }}/safehouse/${{ inputs.service_id }}:"${{ steps.tag_version.outputs.new_tag }}"
        docker push gcr.io/${{ inputs.project_id }}/safehouse/${{ inputs.service_id }}:"${{ steps.tag_version.outputs.new_tag }}"
